### ISSUE TITLE
Throwing Exception from one file and terminating code execution in another

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590hrm#10]
In robust_testing branch, I have file_io.py and process_data.py. process_data.py imports the read_data function from file_io.py . In read_data I try and catch the open() function to check if the file actually exists. I was wondering how to stop execution of process_data if the file actually does not exist and the IOError exception is thrown by open (in read_data).

**Comment by dward2** [comment]
When you say you want to stop the execution of process_data, where do you want to stop it?  

The idea of catching is exceptions is so that the program can respond in an appropriate way and hopefully continue running if necessary.  If the file doesn't exist, do you want the `read_data` function to do anything to try and recover?  Based on your question and how your code is structured, I'm guessing you don't want `read_data` to try and solve anything.  And, since you cannot easily stop the calling code in `process_data.py` from the `read_data` function, don't catch the exception in `read_data`.  When it hits the exception, let it end in an error and send the exception back to where it was called (`__init__` of the `ECG_data` class).

Now, if you wanted the `__init__` function of the ECG_data class to be able to handle the exception, you could put a try-except command around the call to `read_data`.  But, unless there is code you want to add to `__init__` to save the read failure, I would again just let the exception pass up the call stack to the original call to `ECG_data` in the `main()` program.  

I would catch the exception in `main()`.  It is here where you are entering the file name and it is here that you can gracefully end the program if the file doesn't exist.  

```
def main():
    try:
        x = ECG_data('./test_data/test_daXta1.csv')
    except IOError:
        print("File Not Found")
        return  # since this is the main procedure, returning will end the program
    print (x.time)
    etc....
```
Does that make sense?  Give it a try and let me know if you have any questions about my explanation.

**Comment by kaseykwong** [comment]
Ah that makes sense. So if I was to write a test function to check the capabilities of the overall program to identify if a data file doesn't exist, I could test the main function and check that it throws the IOError exception in the even of a nonexistent input file.

**Comment by dward2** [comment]
Or, you can still test the `read_data` file to see if it throws an exception.  See <https://github.com/mlp6/Medical-Software-Design/blob/master/Lectures/Exceptions_ExitCodes_Logging.md#testing-that-your-code-throws-an-exception>.  You would call `read_main` in place of `func_that_raises_type_error'` and `bad_input` would be the name of a non-existent file.
